### ISSUE TITLE
META.json is missing a brace, making it invalid JSON

### ISSUE THREAD

**Issue by keith4** [stockholmuniversity/SU-API-Icinga2-perl#10]
META.json is missing a closing brace, making it invalid JSON. This causes tools that autodownload/build it to fail (e.g., Debian's dh-make-perl).

**Comment by keith4** [comment]
More accurately, the "repository" section is missing a closing brace (line 61)

**Comment by Snorlena** [comment]
@keith4 
It's corrected now. Thanks for notifying.
